mybatis:
  type-aliases-package: com.sodagroup.pojo
  # 驼峰转发开启
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml




spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudmusic?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234567
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
files:
  upload:
    path: D:\Development\codes\CloudeMusic\src\main\resources\static
